# Generated by Django 3.0 on 2020-09-21 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_app.Standard')),
            ],
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('videofile', models.FileField(null=True, upload_to='staticfiles/media_root/videos/', verbose_name='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='staticfiles/static_root/image/')),
                ('thumbnail_image', models.ImageField(blank=True, null=True, upload_to='staticfiles/static_root/thumbnail/')),
                ('url_field', models.URLField()),
                ('active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_app.Chapter')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=50)),
                ('user_type', models.CharField(choices=[('0', 'Admin'), ('1', 'Teacher'), ('2', 'User')], max_length=50)),
                ('active', models.BooleanField(default=False)),
                ('device_id', models.CharField(max_length=255)),
                ('firebase_token', models.CharField(max_length=255)),
                ('login_from', models.CharField(choices=[('0', 'Web'), ('1', 'App')], max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('contact_no_1', models.DecimalField(decimal_places=0, max_digits=10)),
                ('whatsapp_no', models.DecimalField(decimal_places=0, max_digits=10)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='staticfiles/static_root/image/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_app.Subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('0', 'Male'), ('1', 'Female')], max_length=6)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('present_country', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='staticfiles/static_root/image/')),
                ('guardian_name', models.CharField(max_length=255)),
                ('guardian_relation', models.CharField(max_length=50)),
                ('contact_no', models.DecimalField(decimal_places=0, max_digits=10)),
                ('whatsapp_no', models.DecimalField(decimal_places=0, max_digits=10)),
                ('course_type', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_app.Standard')),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_app.Syllabus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_app.User')),
            ],
        ),
        migrations.AddField(
            model_name='standard',
            name='syllabus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_app.Syllabus'),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='staticfiles/static_root/image/')),
                ('pdf', models.FileField(upload_to='staticfiles/static_root/pdf')),
                ('remark', models.CharField(max_length=200)),
                ('uploaded_by', models.CharField(choices=[('0', 'Admin'), ('1', 'Teacher'), ('2', 'User')], max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_app.Chapter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('material_type', models.CharField(choices=[('0', 'Study Material'), ('1', 'Questionnaire'), ('2', 'Previous year Question')], max_length=50)),
                ('url_field', models.URLField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='staticfiles/static_root/image/')),
                ('thumbnail_image', models.ImageField(blank=True, null=True, upload_to='staticfiles/static_root/thumbnail/')),
                ('pdf', models.FileField(upload_to='staticfiles/static_root/pdf')),
                ('active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_app.Chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='staticfiles/static_root/image/')),
                ('pdf', models.FileField(upload_to='staticfiles/static_root/pdf')),
                ('remark', models.CharField(max_length=200)),
                ('uploaded_by', models.CharField(choices=[('0', 'Admin'), ('1', 'Teacher'), ('2', 'User')], max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_app.Chapter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_app.User')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_app.Subject'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_app.Teacher'),
        ),
    ]
