# Generated by Django 3.1.1 on 2020-09-22 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0003_auto_20200922_0640'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='staticfiles/static_root/image/')),
                ('description', models.TextField()),
                ('send_to', models.CharField(choices=[('0', 'Teacher'), ('1', 'Student')], max_length=25)),
            ],
        ),
    ]
