# Generated by Django 3.0 on 2021-02-28 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0003_auto_20201229_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='syllabus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms_app.Syllabus'),
        ),
        migrations.AddField(
            model_name='file',
            name='standard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms_app.Standard'),
        ),
        migrations.AddField(
            model_name='file',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms_app.Subject'),
        ),
        migrations.AddField(
            model_name='file',
            name='syllabus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms_app.Syllabus'),
        ),
        migrations.AddField(
            model_name='question_paper',
            name='standard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms_app.Standard'),
        ),
        migrations.AddField(
            model_name='question_paper',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms_app.Subject'),
        ),
        migrations.AddField(
            model_name='question_paper',
            name='syllabus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms_app.Syllabus'),
        ),
        migrations.AddField(
            model_name='study_material',
            name='standard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms_app.Standard'),
        ),
        migrations.AddField(
            model_name='study_material',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms_app.Subject'),
        ),
        migrations.AddField(
            model_name='study_material',
            name='syllabus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms_app.Syllabus'),
        ),
        migrations.AddField(
            model_name='subject',
            name='syllabus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms_app.Syllabus'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='standard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms_app.Standard'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms_app.Subject'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='documents',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms_app.Chapter'),
        ),
        migrations.AlterField(
            model_name='file',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms_app.Chapter'),
        ),
        migrations.AlterField(
            model_name='question_paper',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='question_paper',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms_app.Chapter'),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='standard',
            name='syllabus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms_app.Syllabus'),
        ),
        migrations.AlterField(
            model_name='study_material',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='study_material',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms_app.Chapter'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='standard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms_app.Standard'),
        ),
        migrations.AlterField(
            model_name='video',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms_app.Chapter'),
        ),
        migrations.AlterField(
            model_name='video',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms_app.Subject'),
        ),
    ]
