# Generated by Django 3.0 on 2021-03-07 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0004_auto_20210228_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='vimeo_video',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
