# Generated by Django 3.0 on 2020-09-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0004_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='staticfiles/image/'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='pdf',
            field=models.FileField(upload_to='staticfiles/pdf'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='staticfiles/image/'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='pdf',
            field=models.FileField(upload_to='staticfiles/pdf'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to='staticfiles/thumbnail/'),
        ),
        migrations.AlterField(
            model_name='file',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='staticfiles/image/'),
        ),
        migrations.AlterField(
            model_name='file',
            name='pdf',
            field=models.FileField(upload_to='staticfiles/pdf'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='staticfiles/image/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='staticfiles/image/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='staticfiles/image/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='staticfiles/image/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to='staticfiles/thumbnail/'),
        ),
    ]
