# Generated by Django 3.0 on 2020-09-22 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0005_auto_20200922_1039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'verbose_name': 'Chapter', 'verbose_name_plural': 'Chapters'},
        ),
    ]
