# Generated by Django 3.0 on 2020-09-22 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0006_auto_20200922_1056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documents',
            options={'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
        migrations.AlterModelOptions(
            name='syllabus',
            options={'verbose_name': 'Syllabus', 'verbose_name_plural': 'Syllabus'},
        ),
    ]
