# Generated by Django 3.0 on 2020-09-23 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0008_teacher_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='subject',
        ),
        migrations.AddField(
            model_name='teacher',
            name='subject',
            field=models.ManyToManyField(to='lms_app.Subject'),
        ),
    ]
