# Generated by Django 3.0 on 2020-09-23 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0009_auto_20200923_0516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_wise', models.ManyToManyField(to='lms_app.Chapter')),
                ('subject_wise', models.ManyToManyField(to='lms_app.Subject')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='scheme',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='lms_app.Scheme'),
            preserve_default=False,
        ),
    ]
