# Generated by Django 3.0 on 2020-09-23 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0010_auto_20200923_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='syllabus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_app.Syllabus'),
            preserve_default=False,
        ),
    ]
