# Generated by Django 3.0 on 2020-09-23 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0011_subject_syllabus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='syllabus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms_app.Syllabus'),
        ),
    ]
