# Generated by Django 3.0 on 2020-09-23 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0012_auto_20200923_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='syllabus',
        ),
    ]
