# Generated by Django 3.0 on 2020-09-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0013_remove_subject_syllabus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='videofile',
            field=models.FileField(null=True, upload_to='staticfiles/media_root/videos/'),
        ),
    ]
