# Generated by Django 3.0 on 2020-09-24 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0017_remove_subject_syllabus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='subject',
        ),
        migrations.AddField(
            model_name='chapter',
            name='subject',
            field=models.ManyToManyField(to='lms_app.Subject'),
        ),
    ]
