# Generated by Django 3.0 on 2020-09-24 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0019_auto_20200924_0552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheme',
            name='scheme_choice',
        ),
        migrations.AddField(
            model_name='scheme',
            name='scheme_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='scheme',
            name='subject_wise',
        ),
        migrations.AddField(
            model_name='scheme',
            name='subject_wise',
            field=models.ManyToManyField(to='lms_app.Subject'),
        ),
    ]
