# Generated by Django 3.0 on 2020-09-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0020_auto_20200924_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standard',
            name='active',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
