# Generated by Django 3.0 on 2020-09-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0021_auto_20200927_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standard',
            name='active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
