# Generated by Django 3.0 on 2020-10-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0022_auto_20200927_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
