# Generated by Django 3.0 on 2020-10-26 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0028_auto_20201026_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
