# Generated by Django 3.0 on 2020-10-26 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0029_auto_20201026_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
