# Generated by Django 3.0 on 2020-10-28 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0033_auto_20201026_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='subject',
            field=models.ManyToManyField(blank=True, to='lms_app.Subject'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
    ]
