# Generated by Django 3.0 on 2020-10-28 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0035_auto_20201028_0605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='gender',
        ),
    ]
