# Generated by Django 3.0 on 2020-10-29 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0038_auto_20201029_0430'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='present_country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
