# Generated by Django 3.0 on 2020-10-29 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0039_student_present_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='scheme',
        ),
    ]
