# Generated by Django 3.0 on 2020-11-04 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0041_auto_20201102_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='subject',
            field=models.ManyToManyField(blank=True, to='lms_app.Subject'),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
