# Generated by Django 3.0 on 2020-11-04 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0044_auto_20201104_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='city',
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lms_app.Country'),
        ),
    ]
