# Generated by Django 3.0 on 2020-11-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0045_auto_20201104_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documents',
            name='material_type',
            field=models.CharField(blank=True, choices=[('0', 'Study Material'), ('1', 'Questionnaire'), ('2', 'Previous year Question')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='documents',
            name='url_field',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
