# Generated by Django 3.0 on 2020-10-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201026_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='device_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='firebase_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='login_from',
            field=models.CharField(blank=True, choices=[('0', 'Web'), ('1', 'App')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('0', 'Admin'), ('1', 'Teacher'), ('2', 'Student')], max_length=50, null=True),
        ),
    ]
